### ISSUE TITLE
Change which FST to use in Itwewîna

### ISSUE THREAD

**Issue by eddieantonio** [eddieantonio/recording-validation-interface#13]
It should be using an HFST file, but it's using an old XFST file:

```sh
FSTLOC=/srv/apps/nds/gtsvn/langs/crk

syl2sro() {
	# descriptive analyzer (vs. normative):
	#  - allows for orthographical fuzziness
	# normative generator
	#  - genrates standard orthography
	hfst-lookup -q ${FSTLOC}/src/orthography/Cans-to-Latn.lookup.hfst |\
		 cut -f2 | tr -d '[[:space:]]' |\
		 hfst-lookup -q ${FSTLOC}/src/analyser-gt-desc.hfst |\
		 head -2 | cut -f2 | hfst-lookup -q ${FSTLOC}/src/generator-gt-norm.hfst |\
		 tr -s '\n' | cut -f2
}

sro2syl() {
	# transform SRO to syllabics
	hfst-lookup -q ${FSTLOC}/src/orthography/Latn-to-Cans.lookup.hfst |\
		 tr -s '\n' | cut -f2 | uniq
}

# vim:set ft=sh:
```

```yaml
Morphology:
  # normative
  crk:
    tool: *HLOOKUP
    file: [*OPT, '/crk/bin/analyser-dict-gt-desc.hfstol']
    inverse_file: [*OPT, '/crk/bin/generator-dict-gt-norm.hfstol']
    format: 'hfst'
    options: &MORPHOLOGY_OPTS
      tagProcessor: "configs/language_specific_rules/crk_tags.py:process_crk_analysis"
      compoundBoundary: "+Use/Circ#"
      derivationMarker: "+Der"
      tagsep: '+'
      inverse_tagsep: '+'
  # crkMacro (omitted)
  # syllabics
  crkS:
    tool: *HLOOKUP
    file: [*FSTLOC, '/crk/src/generator-gt-norm.hfst']
    inverse_file: [*FSTLOC, '/crk/src/orthography/Latn-to-Cans.lookup.hfst']
    format: 'hfst'
    options: *MORPHOLOGY_OPTS
```

Test it with 	ᐚᐸᒣᐤ (wâpamêw) ( *wâpam-* +  Verb +  Transitive Animate +  Imperative +  Immediate +  Actor: 2st Person Singular +  Goal: 3rd Person Singular)
